In [22]:
import pickle
import numpy as np

In [23]:
ohe_sex = pickle.load(open("model/ohe_sex.pkl", "rb"))
ohe_embarked = pickle.load(open("model/ohe_embarked.pkl", "rb"))
clf = pickle.load(open("model/clf.pkl", "rb"))

In [102]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([3, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [103]:
test_input


array([[3, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [104]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_sex

c:\Users\kafar\OneDrive\Documents\Machine Learning\mlenv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 1.]])

In [105]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [106]:
test_input_embarked

array([[0., 0., 1.]])

In [107]:
test_input_age = test_input[:, 2].reshape(1,1)

In [108]:
test_input_transformed = np.concatenate((test_input[:, [0, 3, 4, 5]], test_input_age, test_input_sex, test_input_embarked), axis = 1)

In [109]:
test_input_transformed.shape

(1, 10)

In [110]:
clf.predict(test_input_transformed)

array([1])